# yml 파일 포맷의 version 설정
version: "3.7"

# 띄울 컨테이너 목록
services:

  backend:
    env_file:
      - ./settings/.env.production
    # 환경 설정 부분
    command: bash -c "python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 ainterview.asgi:application"
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ./backend:/backend
    # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - ai_net
    expose:
      - 8000

  nginx:
    container_name: nginx
    build:
      # context : 현재 폴더의 frontend 폴더에 있는 도커파일을 쓰겠다.
      context: ./frontend
    restart: always
    # 가상 네트워크 연결
    networks:
      - ai_net
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    tty: true
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  
  certbot: #certbot 컨테이너 추가
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq_service
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
    expose:
      - 5672
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - backend
    networks:
      - ai_net

  celery:
    container_name: celery_service
    env_file:
      - ./settings/.env.production
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    # command: sh -c "celery -A ainterview worker -l info --pool=solo"
    command: sh -c "celery -A ainterview worker -l info"

    networks:
      - ai_net
    depends_on:
      - rabbitmq
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ai_net
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3060:3000"
    networks:
      - ai_net
    depends_on:
      - prometheus

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - ai_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --docker_only
    ports:
      - 8080:8080
    networks:
      - ai_net

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - ai_net

networks:
  ai_net:
    external: true

volumes:
  grafana-storage:
