groups:
- name: alertRules
  rules:

# Alert for high CPU usage
  - alert: HighCPUUsage
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
    for: 1m
    labels:
      severity: critical
    annotations:
      title: "Instance {{ $labels.instance }} CPU usage is dangerously high"
      description: "{{ $labels.instance }} CPU usage is at {{ $value }}%. Ensure the service is running correctly."

# Alert for any instance that is unreachable for >2 minutes.
  - alert: ServiceDown
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      title: "Service {{ $labels.instance }} is down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

# Alerts when overloaded
  - alert: HighLoad
    expr: node_load1 / count(node_cpu_seconds_total{mode="system"}) > 1.5
    for: 2m
    labels:
      severity: warning
    annotations:
      title: "High load on instance {{ $labels.instance }}"
      description: "The system load is high on instance {{ $labels.instance }}. Current load is {{ $value }}."