global:
  scrape_interval:     15s
  evaluation_interval: 15s

  rule_files:
    - "alert_rules.yml"

  alerting:
    alertmanagers:
      - static_configs:
          - targets:
              - alertmanager:9093

scrape_configs:
  - job_name: 'django'
    scrape_interval: 5s
    static_configs:
      # targeted at localhost:8000/metrics
      - targets: ['backend:8000']

  # node exporter at nodeexporter:9100/metrics
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

