name: Deploy to EC2
on:
  pull_request:
    branches: [ main ]

jobs:

  build_and_deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: create env file
      run: |
        mkdir -p settings
        echo "${{ secrets.DJANGO_SECRET_KEY }}" >> settings/.env.production
        echo "${{ secrets.DJANGO_SETTINGS_MODULE }}" >> settings/.env.production
        echo "{{ secrets.GPT_API_KEY }}" >> settings/.env.production
        echo "{{ secrets.HOST_IP }}" >> settings/.env.production
        echo "{{ secrets.MYSQL_NAME }}" >> settings/.env.production
        echo "{{ secrets.MYSQL_USER }}" >> settings/.env.production
        echo "{{ secrets.MYSQL_PASSWORD }}" >> settings/.env.production
        echo "{{ secrets.HOST }}" >> settings/.env.production
        echo "{{ secrets.MY_AWS_ACCESS_KEY }}" >> settings/.env.production
        echo "{{ secrets.MY_AWS_SECRET_ACCESS_KEY }}" >> settings/.env.production
        echo "{{ secrets.AWS_STORAGE_BUCKET_NAME }}" >> settings/.env.production
        echo "{{ secrets.AWS_S3_CUSTOM_DOMAIN }}" >> settings/.env.production
        echo "{{ secrets.FILE_URL }}" >> settings/.env.production
        
    - name: Set alertmanager YML
      run: |
          mkdir -p alertmanager
          echo "${{ secrets.ALERTMANAGER_YML }}" | base64 --decode > alertmanager/alertmanager.yml
          find alertmanager
        
    - name: create remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SECRET_KEY }}
        script: mkdir -p /home/ubuntu/Docker

    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr
        remote_path: /home/ubuntu/Docker
        remote_host: ${{ secrets.AWS_HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.AWS_SECRET_KEY }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SECRET_KEY }}
        script: |
          sh /home/ubuntu/Docker/config/scripts/deploy.sh
